/*
 * Author: Bui Quang Huy
 * Email: huybq@falcongames.com
 * Company: Falcon Games
 * Date: 2025-09-25
 */

using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.Localization;

namespace Falcon.Modules.UnityLocalization.Editor
{
    public static class ULocGeneratorScript
    {
        private const string Namespace = "ULoc";
        private const string OutputDir = @"Assets\FalconAssets\Modules\UnityLocalization";
        private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
        {
            // Primary keywords
            "abstract","as","base","bool","break","byte","case","catch","char","checked","class",
            "const","continue","decimal","default","delegate","do","double","else","enum","event",
            "explicit","extern","false","finally","fixed","float","for","foreach","goto","if",
            "implicit","in","int","interface","internal","is","lock","long","namespace","new",
            "null","object","operator","out","override","params","private","protected","public",
            "readonly","ref","return","sbyte","sealed","short","sizeof","stackalloc","static",
            "string","struct","switch","this","throw","true","try","typeof","uint","ulong",
            "unchecked","unsafe","ushort","using","virtual","void","volatile","while",
            // Contextual + newer keywords
            "add","and","async","await","by","descending","dynamic","equals","file","from","global",
            "group","init","into","join","let","managed","nameof","nint","not","nuint","on","or",
            "orderby","partial","record","remove","required","scoped","select","set","unmanaged",
            "value","var","when","where","with","yield"
        };

        public static void BuildCodeForCollection(StringTableCollection col)
        {
            if (col == null) throw new ArgumentNullException(nameof(col));
            
            var sb = new StringBuilder(32_000);
            var tableName = col.TableCollectionName;
            var className = SanitizeIdentifier(tableName, pascalCase: true);
            
            var shared = col.SharedData;
            if (shared == null || shared.Entries == null || shared.Entries.Count == 0)
            {
                sb.Append(GenEmpty(Namespace, SanitizeIdentifier(col.TableCollectionName, true)));
            }
            else
            {
                sb.AppendLine(
                    "// <auto-generated> Generated by ULocGeneratorScript. Do not edit manually. </auto-generated>");
                sb.AppendLine("#nullable enable");
                sb.AppendLine("using UnityEngine.Localization.Settings;");
                sb.AppendLine("using Falcon.Modules.UnityLocalization.Runtime;");
                sb.AppendLine();
                sb.AppendLine($"namespace {Namespace}");
                sb.AppendLine("{");
                var usedPropNames = new HashSet<string>();

                sb.AppendLine($"    public static class {className}");
                sb.AppendLine("    {");

                foreach (var entry in shared.Entries.OrderBy(e => e.Key))
                {
                    var originalKey = entry.Key;
                    var safeProp = SanitizeIdentifier(originalKey, pascalCase: false);
                    safeProp = Disambiguate(safeProp, usedPropNames);
                
                    sb.AppendLine(
                        $"        public static ULocEntry {safeProp} => new ULocEntry(\"{EscapeString(tableName)}\", \"{EscapeString(originalKey)}\");");
                }

                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine("}");
                sb.AppendLine("#nullable restore");
            }
            
            var outPath = Path.Combine(OutputDir, $"{className}.cs");
            File.WriteAllText(outPath, sb.ToString(), new UTF8Encoding(false));
            AssetDatabase.ImportAsset(outPath);
            AssetDatabase.Refresh();
            EditorUtility.DisplayDialog("ULoc Generator", $"Generated:\n{outPath}", "OK");
        }

        private static string GenEmpty(string ns, string className)
        {
            return
                $@"// <auto-generated> Generated by ULocGeneratorScript. Do not edit manually. </auto-generated>
#nullable enable
using UnityEngine.Localization.Settings;

namespace {ns}
{{
    public static class {className}
    {{
        // (Empty) No entries in this StringTableCollection.
    }}
}}
#nullable restore
";
        }
        
        private static string SanitizeIdentifier(string raw, bool pascalCase)
        {
            if (string.IsNullOrEmpty(raw)) return "_";

            var parts = raw
                .Split(
                    new[]
                    {
                        ' ', '\t', '\n', '\r', '-', '.', ',', ':', ';', '/', '\\', '|', '@', '#', '!', '?', '(', ')',
                        '[', ']', '{', '}', '\'', '\"'
                    }, StringSplitOptions.RemoveEmptyEntries)
                .ToList();

            if (parts.Count == 0) parts.Add("_");

            for (int i = 0; i < parts.Count; i++)
            {
                var p = parts[i];
                var filtered = new StringBuilder(p.Length);
                foreach (var ch in p)
                    if (char.IsLetterOrDigit(ch) || ch == '_')
                        filtered.Append(ch);
                var s = filtered.Length == 0 ? "_" : filtered.ToString();
                if (pascalCase) s = ToPascal(s);
                else if (i == 0) s = ToCamel(s);
                else s = ToPascal(s);
                parts[i] = s;
            }

            var id = string.Concat(parts);
            if (id.Length == 0 || char.IsDigit(id[0])) id = "_" + id;

            if (CSharpKeywords.Contains(id)) id = "@" + id;

            return id;
        }

        private static string Disambiguate(string name, HashSet<string> used)
        {
            var n = name;
            int idx = 1;
            while (!used.Add(n))
            {
                idx++;
                n = $"{name}_{idx}";
            }

            return n;
        }

        private static string ToPascal(string s) => string.IsNullOrEmpty(s) ? s : char.ToUpperInvariant(s[0]) + s[1..];
        private static string ToCamel(string s) => string.IsNullOrEmpty(s) ? s : char.ToLowerInvariant(s[0]) + s[1..];

        private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
