/*
 * Author: Bui Quang Huy
 * Email: huybq@falcongames.com
 * Company: Falcon Games
 * Date: 2026-07-28
 */

using System.Collections.Generic;
using System.Linq;
using Sirenix.OdinInspector;
using UnityEngine;

namespace Falcon.Shared.BaseBooster
{
    /// <summary>
    /// Danh sách type booster của project. Tên/mô tả lấy theo key localize quy ước, không lưu ở đây.
    /// </summary>
    [CreateAssetMenu(menuName = "Falcon/Booster/Booster Info", fileName = "BoosterInfoSO")]
    public class BoosterInfoSO : ScriptableObject
    {
        [SerializeField] private List<string> types = new();

        public IEnumerable<string> Types => types;

#if UNITY_EDITOR
        // Sinh BoosterConst.cs cạnh asset này, mỗi type 1 const.
        [Button("Generate BoosterConst")]
        private void GenerateBoosterConst()
        {
            var sb = new System.Text.StringBuilder();
            sb.AppendLine("// <auto-generated> Sinh bởi BoosterInfoSO.GenerateBoosterConst, đừng sửa tay.");
            sb.AppendLine("namespace Falcon.Shared.BaseBooster");
            sb.AppendLine("{");
            sb.AppendLine("    public static class BoosterConst");
            sb.AppendLine("    {");
            foreach (var type in Types.Where(t => !string.IsNullOrWhiteSpace(t)).Distinct())
                sb.AppendLine($"        public const string {ToConstName(type)} = \"{type}\";");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            var dir = System.IO.Path.GetDirectoryName(UnityEditor.AssetDatabase.GetAssetPath(this));
            var path = $"{dir}/BoosterConst.cs";
            System.IO.File.WriteAllText(path, sb.ToString());
            UnityEditor.AssetDatabase.ImportAsset(path);
            Debug.Log($"[BoosterInfoSO] Generated {path}");
        }

        // "booster_1" -> "BOOSTER_1", ký tự lạ thành '_'
        private static string ToConstName(string type)
        {
            var name = new string(type.Select(c => char.IsLetterOrDigit(c) ? char.ToUpperInvariant(c) : '_').ToArray());
            return char.IsDigit(name[0]) ? $"_{name}" : name;
        }
#endif
    }
}
