/*
     * Author: ngocdx
     * Email: ngocdx@falcongames.com
     * Company: Falcon Games
     * Date: 2025-06-04
     */

using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text.RegularExpressions;

namespace Falcon.Modules.Core.SaveLoad.Editor
{
	using BayatGames.SaveGamePro;

	public class SaveLoadConfigsEditor : EditorWindow
	{
		private string _saveLoadDefaultPass;
		private string _saveLoadRandomKey;

		private static readonly string kSaveLoadPath = @"FalconAssets\Modules\Core\Utils\SaveLoad\SaveLoadConfigs.cs";

		[MenuItem(@"Falcon/Modules/SaveLoad/Update Configs", false, 101)]
		public static void ShowWindow()
		{
			var window = GetWindow<SaveLoadConfigsEditor>("SaveLoad Configs");
			window.minSize = new Vector2(400, 150);
			window.maxSize = new Vector2(400, 150);
		}
		
		[MenuItem(@"Falcon/Modules/SaveLoad/Clear Data", false, 201)]
		public static void ClearData()
		{
			bool clear = EditorUtility.DisplayDialog(
				"Clearing Saved Data",
				"Are you sure you want to clear all saved data on this device?",
				"Yes", "No");
			if (clear)
			{
				SaveGame.Clear();
			}
		}

		private void OnEnable() { LoadCurrentValues(); }

		void OnGUI()
		{
			GUILayout.Label("SaveLoad Configuration", EditorStyles.boldLabel);
			GUILayout.Space(5);

			_saveLoadDefaultPass = EditorGUILayout.TextField("Encrypted Pass", _saveLoadDefaultPass);
			_saveLoadRandomKey   = EditorGUILayout.TextField("Random Key", _saveLoadRandomKey);

			GUILayout.Space(5);
			if (GUILayout.Button("Apply Changes"))
			{
				ApplyChanges();
			}
		}

		private void LoadCurrentValues()
		{
			string configFilePath = Path.Combine(Application.dataPath, kSaveLoadPath);
			if (File.Exists(configFilePath))
			{
				string fileContent = File.ReadAllText(configFilePath);
				_saveLoadDefaultPass = GetValue(fileContent, "SaveLoadDefaultPass", "Default_Pass");
				_saveLoadRandomKey   = GetValue(fileContent, "SaveLoadRandomKey", "Random_Key");
			}
			else
			{
				_saveLoadDefaultPass = "Default_Pass";
				_saveLoadRandomKey   = "Random_Key";
			}
		}

		private void ApplyChanges()
		{
			if (string.IsNullOrEmpty(_saveLoadDefaultPass) || string.IsNullOrEmpty(_saveLoadRandomKey))
			{
				EditorUtility.DisplayDialog("Cannot Be Empty", "Value cannot be empty", "OK");
				return;
			}

			_saveLoadDefaultPass = _saveLoadDefaultPass.Trim();
			_saveLoadRandomKey   = _saveLoadRandomKey.Trim();

			string configFilePath = Path.Combine(Application.dataPath, kSaveLoadPath);
			var dir = Path.GetDirectoryName(configFilePath);
			if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
			{
				Directory.CreateDirectory(dir);
			}

			string fileContent = $@"/*
 * This file is auto-generated by Falcon.Modules.Core.SaveLoad.Editor.
 * Do not edit this file manually.
 */
namespace Falcon.Modules.Core.SaveLoad.Runtime
{{
	using UnityEngine;

    public sealed class SaveLoadConfigs : ISaveLoadConfigs
    {{
        public string SaveLoadDefaultPass => ""{_saveLoadDefaultPass}"";
        public string SaveLoadRandomKey => ""{_saveLoadRandomKey}"";
    }}

	internal static class SaveLoadRunner
    {{
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]
        static void Initialize()
        {{
            SaveLoadHandler.Configs = new SaveLoadConfigs();
        }}
    }}
}}";

			File.WriteAllText(configFilePath, fileContent);
			AssetDatabase.Refresh();
			EditorUtility.DisplayDialog("Success", "Configuration updated and recompiled!", "OK");
		}

		private string GetValue(string fileContent, string property, string defaultValue)
		{
			string pattern = $"(public string {property} => \")(.*?)(\";)";
			Match  match   = Regex.Match(fileContent, pattern);
			if (match.Success)
			{
				return match.Groups[2].Value;
			}

			return defaultValue;
		}
	}
}
