// <auto-generated> Sinh bởi BoosterInfoSO.GenerateBoosterConst, đừng sửa tay.
namespace Falcon.Shared.BaseBooster
{
    public static class BoosterConst
    {
        public const string BOOSTER_1 = "booster_1";
        public const string BOOSTER_2 = "booster_2";
        public const string BOOSTER_3 = "booster_3";
    }
}
