// <auto-generated> Sinh bởi Audio Config Editor. Đừng sửa tay.
// Đừng gán giá trị cho member: AudioManager tra tên bằng (int)key.

namespace Falcon.Shared.Audio
{
    public enum SoundEnum
    {
        BGM_Home,
        BGM_Level,
        ClaimGold,
        Click,
        HideBox,
        Item_Pick,
        LogoEndgameFX,
        SFX_Object_Collect_Small_1,
        SFX_Object_Collect_Small_2,
        SFX_Object_Collect_Small_3,
        ShowPopupLose,
        ShowPopupWin,
        UIClick,
        buy_success,
    }

    /// Số clip của mỗi key, index theo (int)SoundEnum. >1 nghĩa là address có hậu tố _0.._n.
    public static class SoundEnumVariants
    {
        public static readonly int[] Counts = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 };
    }
}
